### ISSUE TITLE
Errors when running the test suite

### ISSUE THREAD

**Issue by sajith** [atlanticwave-sdx/sdx-controller-client#1]
I checked out the source code, and ran tox off a virtual environment, like so:

```console
$ git clone https://github.com/atlanticwave-sdx/sdx-controller-client.git
$ cd sdx-controller-client
$ python3 -m venv venv
$ source venv/bin/activate
$ python3 -m pip install tox
$ tox
```

That resulted in some errors:

```console
GLOB sdist-make: /home/sajith/projects/atlanticwave-sdx/sdx-controller-client/setup.py
py3 inst-nodeps: /home/sajith/projects/atlanticwave-sdx/sdx-controller-client/.tox/.tmp/package/1/swagger-client-1.0.0.zip
py3 installed: certifi==2022.6.15,coverage==6.4.1,nose==1.3.7,pluggy==1.0.0,py==1.11.0,python-dateutil==2.8.2,randomize==0.14,six==1.16.0,swagger-client @ file:///home/sajith/projects/atlanticwave-sdx/sdx-controller-client/.tox/.tmp/package/1/swagger-client-1.0.0.zip,urllib3==1.26.9
py3 run-test-pre: PYTHONHASHSEED='1056661469'
py3 run-test: commands[0] | nosetests
..EException ignored in: <function ApiClient.__del__ at 0x7fd679532ee0>
Traceback (most recent call last):
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
AttributeError: 'ApiClient' object has no attribute 'pool'
EException ignored in: <function ApiClient.__del__ at 0x7fd679532ee0>
Traceback (most recent call last):
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
AttributeError: 'ApiClient' object has no attribute 'pool'
EException ignored in: <function ApiClient.__del__ at 0x7fd679532ee0>
Traceback (most recent call last):
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
AttributeError: 'ApiClient' object has no attribute 'pool'
.EException ignored in: <function ApiClient.__del__ at 0x7fd679532ee0>
Traceback (most recent call last):
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
AttributeError: 'ApiClient' object has no attribute 'pool'
..EException ignored in: <function ApiClient.__del__ at 0x7fd679532ee0>
Traceback (most recent call last):
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
AttributeError: 'ApiClient' object has no attribute 'pool'
..EException ignored in: <function ApiClient.__del__ at 0x7fd679532ee0>
Traceback (most recent call last):
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
AttributeError: 'ApiClient' object has no attribute 'pool'
EException ignored in: <function ApiClient.__del__ at 0x7fd679532ee0>
Traceback (most recent call last):
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
AttributeError: 'ApiClient' object has no attribute 'pool'
EException ignored in: <function ApiClient.__del__ at 0x7fd679532ee0>
Traceback (most recent call last):
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
AttributeError: 'ApiClient' object has no attribute 'pool'
.EException ignored in: <function ApiClient.__del__ at 0x7fd679532ee0>
Traceback (most recent call last):
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
AttributeError: 'ApiClient' object has no attribute 'pool'
EException ignored in: <function ApiClient.__del__ at 0x7fd679532ee0>
Traceback (most recent call last):
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
AttributeError: 'ApiClient' object has no attribute 'pool'
EException ignored in: <function ApiClient.__del__ at 0x7fd679532ee0>
Traceback (most recent call last):
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
AttributeError: 'ApiClient' object has no attribute 'pool'
EException ignored in: <function ApiClient.__del__ at 0x7fd679532ee0>
Traceback (most recent call last):
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
AttributeError: 'ApiClient' object has no attribute 'pool'
EException ignored in: <function ApiClient.__del__ at 0x7fd679532ee0>
Traceback (most recent call last):
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
AttributeError: 'ApiClient' object has no attribute 'pool'
EException ignored in: <function ApiClient.__del__ at 0x7fd679532ee0>
Traceback (most recent call last):
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
AttributeError: 'ApiClient' object has no attribute 'pool'
EException ignored in: <function ApiClient.__del__ at 0x7fd679532ee0>
Traceback (most recent call last):
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
AttributeError: 'ApiClient' object has no attribute 'pool'
EException ignored in: <function ApiClient.__del__ at 0x7fd679532ee0>
Traceback (most recent call last):
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
AttributeError: 'ApiClient' object has no attribute 'pool'

======================================================================
ERROR: Test case for delete_connection
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/test/test_connection_api.py", line 26, in setUp
    self.api = ConnectionApi()  # noqa: E501
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api/connection_api.py", line 32, in __init__
    api_client = ApiClient()
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api_client.py", line 65, in __init__
    configuration = Configuration()
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/configuration.py", line 32, in __call__
    cls._default = type.__call__(cls)
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/configuration.py", line 51, in __init__
    os.getenv('SDXCONTROLLER_HOST'),
NameError: name 'os' is not defined

======================================================================
ERROR: Test case for getconnection_by_id
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/test/test_connection_api.py", line 26, in setUp
    self.api = ConnectionApi()  # noqa: E501
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api/connection_api.py", line 32, in __init__
    api_client = ApiClient()
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api_client.py", line 65, in __init__
    configuration = Configuration()
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/configuration.py", line 32, in __call__
    cls._default = type.__call__(cls)
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/configuration.py", line 51, in __init__
    os.getenv('SDXCONTROLLER_HOST'),
NameError: name 'os' is not defined

======================================================================
ERROR: Test case for place_connection
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/test/test_connection_api.py", line 26, in setUp
    self.api = ConnectionApi()  # noqa: E501
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api/connection_api.py", line 32, in __init__
    api_client = ApiClient()
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api_client.py", line 65, in __init__
    configuration = Configuration()
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/configuration.py", line 32, in __call__
    cls._default = type.__call__(cls)
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/configuration.py", line 51, in __init__
    os.getenv('SDXCONTROLLER_HOST'),
NameError: name 'os' is not defined

======================================================================
ERROR: Test case for get_link
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/test/test_link_api.py", line 26, in setUp
    self.api = LinkApi()  # noqa: E501
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api/link_api.py", line 32, in __init__
    api_client = ApiClient()
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api_client.py", line 65, in __init__
    configuration = Configuration()
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/configuration.py", line 32, in __call__
    cls._default = type.__call__(cls)
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/configuration.py", line 51, in __init__
    os.getenv('SDXCONTROLLER_HOST'),
NameError: name 'os' is not defined

======================================================================
ERROR: Test case for get_node
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/test/test_node_api.py", line 26, in setUp
    self.api = NodeApi()  # noqa: E501
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api/node_api.py", line 32, in __init__
    api_client = ApiClient()
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api_client.py", line 65, in __init__
    configuration = Configuration()
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/configuration.py", line 32, in __call__
    cls._default = type.__call__(cls)
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/configuration.py", line 51, in __init__
    os.getenv('SDXCONTROLLER_HOST'),
NameError: name 'os' is not defined

======================================================================
ERROR: Test case for get_topology
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/test/test_topology_api.py", line 26, in setUp
    self.api = TopologyApi()  # noqa: E501
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api/topology_api.py", line 32, in __init__
    api_client = ApiClient()
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api_client.py", line 65, in __init__
    configuration = Configuration()
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/configuration.py", line 32, in __call__
    cls._default = type.__call__(cls)
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/configuration.py", line 51, in __init__
    os.getenv('SDXCONTROLLER_HOST'),
NameError: name 'os' is not defined

======================================================================
ERROR: Test case for get_topologyby_version
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/test/test_topology_api.py", line 26, in setUp
    self.api = TopologyApi()  # noqa: E501
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api/topology_api.py", line 32, in __init__
    api_client = ApiClient()
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api_client.py", line 65, in __init__
    configuration = Configuration()
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/configuration.py", line 32, in __call__
    cls._default = type.__call__(cls)
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/configuration.py", line 51, in __init__
    os.getenv('SDXCONTROLLER_HOST'),
NameError: name 'os' is not defined

======================================================================
ERROR: Test case for topology_version
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/test/test_topology_api.py", line 26, in setUp
    self.api = TopologyApi()  # noqa: E501
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api/topology_api.py", line 32, in __init__
    api_client = ApiClient()
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api_client.py", line 65, in __init__
    configuration = Configuration()
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/configuration.py", line 32, in __call__
    cls._default = type.__call__(cls)
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/configuration.py", line 51, in __init__
    os.getenv('SDXCONTROLLER_HOST'),
NameError: name 'os' is not defined

======================================================================
ERROR: Test case for create_user
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/test/test_user_api.py", line 26, in setUp
    self.api = UserApi()  # noqa: E501
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api/user_api.py", line 32, in __init__
    api_client = ApiClient()
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api_client.py", line 65, in __init__
    configuration = Configuration()
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/configuration.py", line 32, in __call__
    cls._default = type.__call__(cls)
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/configuration.py", line 51, in __init__
    os.getenv('SDXCONTROLLER_HOST'),
NameError: name 'os' is not defined

======================================================================
ERROR: Test case for create_users_with_array_input
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/test/test_user_api.py", line 26, in setUp
    self.api = UserApi()  # noqa: E501
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api/user_api.py", line 32, in __init__
    api_client = ApiClient()
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api_client.py", line 65, in __init__
    configuration = Configuration()
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/configuration.py", line 32, in __call__
    cls._default = type.__call__(cls)
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/configuration.py", line 51, in __init__
    os.getenv('SDXCONTROLLER_HOST'),
NameError: name 'os' is not defined

======================================================================
ERROR: Test case for create_users_with_list_input
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/test/test_user_api.py", line 26, in setUp
    self.api = UserApi()  # noqa: E501
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api/user_api.py", line 32, in __init__
    api_client = ApiClient()
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api_client.py", line 65, in __init__
    configuration = Configuration()
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/configuration.py", line 32, in __call__
    cls._default = type.__call__(cls)
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/configuration.py", line 51, in __init__
    os.getenv('SDXCONTROLLER_HOST'),
NameError: name 'os' is not defined

======================================================================
ERROR: Test case for delete_user
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/test/test_user_api.py", line 26, in setUp
    self.api = UserApi()  # noqa: E501
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api/user_api.py", line 32, in __init__
    api_client = ApiClient()
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api_client.py", line 65, in __init__
    configuration = Configuration()
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/configuration.py", line 32, in __call__
    cls._default = type.__call__(cls)
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/configuration.py", line 51, in __init__
    os.getenv('SDXCONTROLLER_HOST'),
NameError: name 'os' is not defined

======================================================================
ERROR: Test case for get_user_by_name
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/test/test_user_api.py", line 26, in setUp
    self.api = UserApi()  # noqa: E501
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api/user_api.py", line 32, in __init__
    api_client = ApiClient()
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api_client.py", line 65, in __init__
    configuration = Configuration()
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/configuration.py", line 32, in __call__
    cls._default = type.__call__(cls)
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/configuration.py", line 51, in __init__
    os.getenv('SDXCONTROLLER_HOST'),
NameError: name 'os' is not defined

======================================================================
ERROR: Test case for login_user
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/test/test_user_api.py", line 26, in setUp
    self.api = UserApi()  # noqa: E501
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api/user_api.py", line 32, in __init__
    api_client = ApiClient()
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api_client.py", line 65, in __init__
    configuration = Configuration()
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/configuration.py", line 32, in __call__
    cls._default = type.__call__(cls)
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/configuration.py", line 51, in __init__
    os.getenv('SDXCONTROLLER_HOST'),
NameError: name 'os' is not defined

======================================================================
ERROR: Test case for logout_user
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/test/test_user_api.py", line 26, in setUp
    self.api = UserApi()  # noqa: E501
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api/user_api.py", line 32, in __init__
    api_client = ApiClient()
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api_client.py", line 65, in __init__
    configuration = Configuration()
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/configuration.py", line 32, in __call__
    cls._default = type.__call__(cls)
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/configuration.py", line 51, in __init__
    os.getenv('SDXCONTROLLER_HOST'),
NameError: name 'os' is not defined

======================================================================
ERROR: Test case for update_user
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/test/test_user_api.py", line 26, in setUp
    self.api = UserApi()  # noqa: E501
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api/user_api.py", line 32, in __init__
    api_client = ApiClient()
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api_client.py", line 65, in __init__
    configuration = Configuration()
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/configuration.py", line 32, in __call__
    cls._default = type.__call__(cls)
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/configuration.py", line 51, in __init__
    os.getenv('SDXCONTROLLER_HOST'),
NameError: name 'os' is not defined

----------------------------------------------------------------------
Ran 24 tests in 0.058s

FAILED (errors=16)
ERROR: InvocationError for command /home/sajith/projects/atlanticwave-sdx/sdx-controller-client/.tox/py3/bin/nosetests (exited with code 1)
__________________________________________________________________________ summary ___________________________________________________________________________
ERROR:   py3: commands failed
```

**Comment by sajith** [comment]
It should be a simple matter of adding a line of `import os` in `swagger_client/configuration.py`, but with that, we get a new set of error messages (errors about something asynchronous, which is much harder to figure out), and a final message saying that "py3: commands succeeded".

This is with Python 3.9, Debian 11.3, commit 426453bf84e9522e857fd78139bb63429b9091cc:

```console
GLOB sdist-make: /home/sajith/projects/atlanticwave-sdx/sdx-controller-client/setup.py
py3 inst-nodeps: /home/sajith/projects/atlanticwave-sdx/sdx-controller-client/.tox/.tmp/package/1/swagger-client-1.0.0.zip
py3 installed: certifi==2022.6.15,coverage==6.4.1,nose==1.3.7,pluggy==1.0.0,py==1.11.0,python-dateutil==2.8.2,randomize==0.14,six==1.16.0,swagger-client @ file:///home/sajith/projects/atlanticwave-sdx/sdx-controller-client/.tox/.tmp/package/1/swagger-client-1.0.0.zip,urllib3==1.26.9
py3 run-test-pre: PYTHONHASHSEED='2233571576'
py3 run-test: commands[0] | nosetests
........................
----------------------------------------------------------------------
Ran 24 tests in 0.077s

OK
Exception ignored in: <function ApiClient.__del__ at 0x7f8b5a097ee0>
Traceback (most recent call last):
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 649, in close
    self._change_notifier.put(None)
  File "/usr/lib/python3.9/multiprocessing/queues.py", line 378, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function ApiClient.__del__ at 0x7f8b5a097ee0>
Traceback (most recent call last):
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 649, in close
    self._change_notifier.put(None)
  File "/usr/lib/python3.9/multiprocessing/queues.py", line 378, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function ApiClient.__del__ at 0x7f8b5a097ee0>
Traceback (most recent call last):
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 649, in close
    self._change_notifier.put(None)
  File "/usr/lib/python3.9/multiprocessing/queues.py", line 378, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function ApiClient.__del__ at 0x7f8b5a097ee0>
Traceback (most recent call last):
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 649, in close
    self._change_notifier.put(None)
  File "/usr/lib/python3.9/multiprocessing/queues.py", line 378, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function ApiClient.__del__ at 0x7f8b5a097ee0>
Traceback (most recent call last):
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 649, in close
    self._change_notifier.put(None)
  File "/usr/lib/python3.9/multiprocessing/queues.py", line 378, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function ApiClient.__del__ at 0x7f8b5a097ee0>
Traceback (most recent call last):
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 649, in close
    self._change_notifier.put(None)
  File "/usr/lib/python3.9/multiprocessing/queues.py", line 378, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function ApiClient.__del__ at 0x7f8b5a097ee0>
Traceback (most recent call last):
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 649, in close
    self._change_notifier.put(None)
  File "/usr/lib/python3.9/multiprocessing/queues.py", line 378, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function ApiClient.__del__ at 0x7f8b5a097ee0>
Traceback (most recent call last):
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 649, in close
    self._change_notifier.put(None)
  File "/usr/lib/python3.9/multiprocessing/queues.py", line 378, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function ApiClient.__del__ at 0x7f8b5a097ee0>
Traceback (most recent call last):
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 649, in close
    self._change_notifier.put(None)
  File "/usr/lib/python3.9/multiprocessing/queues.py", line 378, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor
Exception ignored in: <function ApiClient.__del__ at 0x7f8b5a097ee0>
Traceback (most recent call last):
  File "/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/swagger_client/api_client.py", line 78, in __del__
    self.pool.close()
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 649, in close
    self._change_notifier.put(None)
  File "/usr/lib/python3.9/multiprocessing/queues.py", line 378, in put
    self._writer.send_bytes(obj)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor
__________________________________________________________________________ summary ___________________________________________________________________________
  py3: commands succeeded
  congratulations :)
```

**Comment by sajith** [comment]
What if I switch to pytest from nose?

```console
$ tox -r
GLOB sdist-make: /home/sajith/projects/atlanticwave-sdx/sdx-controller-client/setup.py
py3 recreate: /home/sajith/projects/atlanticwave-sdx/sdx-controller-client/.tox/py3
py3 installdeps: -r/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/requirements.txt, -r/home/sajith/projects/atlanticwave-sdx/sdx-controller-client/test-requirements.txt
py3 inst: /home/sajith/projects/atlanticwave-sdx/sdx-controller-client/.tox/.tmp/package/1/swagger-client-1.0.0.zip
py3 installed: attrs==21.4.0,certifi==2022.6.15,coverage==6.4.1,iniconfig==1.1.1,packaging==21.3,pluggy==1.0.0,py==1.11.0,pyparsing==3.0.9,pytest==7.1.2,python-dateutil==2.8.2,randomize==0.14,six==1.16.0,swagger-client @ file:///home/sajith/projects/atlanticwave-sdx/sdx-controller-client/.tox/.tmp/package/1/swagger-client-1.0.0.zip,tomli==2.0.1,urllib3==1.26.9
py3 run-test-pre: PYTHONHASHSEED='3282959102'
py3 run-test: commands[0] | pytest
============================= test session starts ==============================
platform linux -- Python 3.9.2, pytest-7.1.2, pluggy-1.0.0
cachedir: .tox/py3/.pytest_cache
rootdir: /home/sajith/projects/atlanticwave-sdx/sdx-controller-client
collected 24 items                                                             

test/test_api_response.py .                                              [  4%]
test/test_connection.py .                                                [  8%]
test/test_connection_api.py ...                                          [ 20%]
test/test_link.py .                                                      [ 25%]
test/test_link_api.py .                                                  [ 29%]
test/test_location.py .                                                  [ 33%]
test/test_node.py .                                                      [ 37%]
test/test_node_api.py .                                                  [ 41%]
test/test_port.py .                                                      [ 45%]
test/test_topology.py .                                                  [ 50%]
test/test_topology_api.py ...                                            [ 62%]
test/test_user.py .                                                      [ 66%]
test/test_user_api.py ........                                           [100%]

============================== 24 passed in 0.20s ==============================
___________________________________ summary ____________________________________
  py3: commands succeeded
  congratulations :)
```

I don't know what that means though...
